---
blank_issues_enabled: false
contact_links:
  - name: "\U0001F914 Question about an Expo Config Plugin"
    about: >-
      If you have a question about an Expo Config Plugin, please ask it on the
      forums, discord, Twitter, or Stack Overflow.
    url: 'https://forums.expo.io/'
  - about: E2E tests and automation for mobile
    name: "\U0001F4E6 detox issues"
    url: 'https://github.com/wix/Detox/issues'
  - about: FFmpeg Kit for React Native
    name: "\U0001F4E6 ffmpeg-kit-react-native issues"
    url: 'https://github.com/tanersener/ffmpeg-kit/issues'
  - about: Adjust React Native SDK
    name: "\U0001F4E6 react-native-adjust issues"
    url: 'https://github.com/adjust/react_native_sdk/issues'
  - about: React Native Bluetooth Low Energy library
    name: "\U0001F4E6 react-native-ble-plx issues"
    url: 'https://github.com/Polidea/react-native-ble-plx/issues'
  - about: >-
      A module provides upload, download, and files access API. Supports file
      stream read/write for process large files.
    name: "\U0001F4E6 react-native-blob-util issues"
    url: 'https://github.com/RonRadtke/react-native-blob-util/issues'
  - about: iOS 10 CallKit and Android ConnectionService Framework For React Native
    name: "\U0001F4E6 react-native-callkeep issues"
    url: 'https://github.com/react-native-webrtc/react-native-callkeep/issues'
  - about: Programmatically change the app icon in React Native.
    name: "\U0001F4E6 react-native-dynamic-app-icon issues"
    url: 'https://github.com/idearockers/react-native-dynamic-app-icon/issues'
  - about: React Native wrapper for the Google Cast SDK for iOS and Android
    name: "\U0001F4E6 react-native-google-cast issues"
    url: >-
      https://github.com/react-native-google-cast/react-native-google-cast/issues
  - about: 'A react native PDF view component, support ios and android platform'
    name: "\U0001F4E6 react-native-pdf issues"
    url: 'https://github.com/wonday/react-native-pdf/issues'
  - about: A react-native interface for Touch 3D home screen quick actions
    name: "\U0001F4E6 react-native-quick-actions issues"
    url: 'https://github.com/jordanbyron/react-native-quick-actions/issues'
  - about: WebRTC for React Native
    name: "\U0001F4E6 react-native-webrtc issues"
    url: 'https://github.com/react-native-webrtc/react-native-webrtc/issues'
